### ISSUE TITLE
Readme links broken

### ISSUE THREAD

**Issue by petr-tik** [aevri/mel#1]
The [Mayo Clinic](https://github.com/aevri/mel/blob/master/1) leads to a 404 page

[UK National Health Service](http://www.nhs.uk/be-clear-on-cancer/assets/BeClearOnCancer_skincancer_leaflet.pdf) points to a 404 page.

Please fix the Mayo Clinic link and consider adding a pdf to GitHub file storage, so you can point to a permanent file.

**Comment by aevri** [comment]
Hiya! Have fixed Mayo Clinic link and updated NHS link to reflect similar content to the Mayo Clinic link - explaining the emphasis on "new and changing moles". Thanks!
